### PR TITLE
Better ES Classes support

### PR DESCRIPTION
**Pull request by tandy-1000**
Nothing here yet.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

TODO:
   - [ ] generators / iterators
   - [ ] `extends`, sub-classing, mix-ins
   - [ ] `super`, super-classing, species
   - [ ] field declarations, public / private

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Feel free to split the PR into multiple ones if you think is better,
splitting a heavy rock into tiny pieces makes it easy to work with maybe...

**Comment by juancarlospaco** [comment]
How the progress is going, is it doable ? @tandy-1000
🙂

**Comment by tandy-1000** [comment]
No progress, I opened this more as a TODO for myself, feel free to close if you need :)
I will be available to work on this by the end of May, when university is over.

**Comment by juancarlospaco** [comment]
Chill out bot... 🤖

**Pull request closed without merging**
